POST http://localhost:3001/api/readinglists
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QxQGV4YW1wbGUuY29tIiwiaWQiOjcsImlhdCI6MTc3NDY4MTk4Nn0.TtqiA3mi-3mgYhjIEIs0-IU_TLFPmAsIbSgE9A81vvo
Content-Type: application/json

{
  "blogId": 13,
  "userId": 7
}