PUT http://localhost:3001/api/readinglists/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hdHRpbWVpa2FsYWluZW5AaG90bWFpbC5jb20iLCJpZCI6MywiaWF0IjoxNzc0MDcwNzMyfQ.eRg31QH2a4dvWi6XZFIl1KGnI8Wb4qncxX8rraboQgI
Content-Type: application/json

{
  "blog_read": true
}